### ISSUE TITLE
Getting node.getIterator is not a function error

### ISSUE THREAD

**Issue by kmcaloon** [postcss/postcss-scss#116]
Just added `syntax: 'postcss-scss` to my `postcss.config.js` file and it is throwing the following error:

```
PluginError [TypeError]: node.getIterator is not a function
    at LazyResult.visitTick (/Applications/MAMP/htdocs/dartdrones/wp-content/themes/dartdrones.com/node_modules/postcss/lib/lazy-result.js:484:33)
    at LazyResult.runAsync (/Applications/MAMP/htdocs/dartdrones/wp-content/themes/dartdrones.com/node_modules/postcss/lib/lazy-result.js:372:30)
```

Here is my full config:

```
module.exports = {
  syntax: 'postcss-scss',
  plugins: {
    'postcss-import': {
      from: 'src/global.css',
    },
    // 'postcss-nested': {},
    'autoprefixer': {
      add: true,
    },
    'postcss-reporter': { clearReportedMessages: true },
    ...process.env.NODE_ENV == 'development' ? {} : {
      '@fullhuman/postcss-purgecss': {
        content: [
          './src/**/*.php',
          './src/**/*.js',
        ]
      },
    },
    'cssnano': {
      preset: [ 'default', {} ],
    }
  }
};
```

Not quite sure where to start troubleshooting. Any ideas what might be going on?

**Comment by ai** [comment]
You have different PostCSS versions in the system. Try to check `npm ls | grep postcss`

**Comment by MJSHANZ** [comment]
Facing the same issue any inputs will be really helpful 

@kmcaloon @ai
