### ISSUE TITLE
Unclosed bracket error in url(fqdn) preceded by a slash on the same line 

### ISSUE THREAD

**Issue by jleclanche** [postcss/postcss-scss#142]
Original issue: https://github.com/vercel/next.js/issues/21461

Reproduction repo: https://github.com/jleclanche/nextjs-issue-21461

Reduced to the following:

```js
// test.js
// Run with `node test.js`
const { parse } = require("postcss-scss");

// Succeeds
parse(".test{background:center/auto,\nurl(https://example.com/test.png)}");

// Succeeds
parse(".test{background:center/auto,url(/test.png)}");

// FAILS
/*
CssSyntaxError: <css input>:1:33: Unclosed bracket
    at Input.error (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/input.js:148:16)
    at ScssParser.unclosedBracket (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/parser.js:532:22)
    at ScssParser.other (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/parser.js:152:35)
    at ScssParser.parse (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/parser.js:72:16)
    at Object.scssParse [as parse] (/home/adys/nextjs-issue-21461/node_modules/postcss-scss/lib/scss-parse.js:9:10)
    at Object.<anonymous> (/home/adys/nextjs-issue-21461/test.js:5:15)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12) {
  reason: 'Unclosed bracket',
  source: '.test{background:center/auto,url(https://example.com/test.png)}',
  line: 1,
  column: 33,
  endLine: 1,
  endColumn: 34,
  input: {
    line: 1,
    column: 33,
    endLine: 1,
    endColumn: 34,
    source: '.test{background:center/auto,url(https://example.com/test.png)}'
  }
}
*/
console.log(parse(".test{background:center/auto,url(https://example.com/test.png)}"));
```

**Comment by ai** [comment]
I will have a quick look today, but seems like I will able to look deeply only after my vacation (2 weeks after).

**Comment by jleclanche** [comment]
Looking at the postcss parser, it's what i suspected, it detects a comment from the url...

```js
[
  [ 'word', 'background', 6, 15 ],
  [ ':', ':', 16 ],
  [ 'word', 'center/auto,url', 17, 31 ],
  [ '(', '(', 32 ],
  [ 'word', '/test.png', 33, 41 ],
  [ ')', ')', 42 ],
  [ '}', '}', 43 ]
]
```

Running the same with the newline before the url() yields a better token list:

```js
[
  [ 'word', 'background', 6, 15 ],
  [ ':', ':', 16 ],
  [ 'word', 'center/auto,', 17, 28 ],
  [ 'space', '\n' ],
  [ 'word', 'url', 30, 32 ],
  [ 'brackets', '(https://example.com/test.png)', 33, 62 ],
  [ '}', '}', 63 ]
]
```

**Comment by jleclanche** [comment]
Looking at the postcss parser, it's what i suspected, it detects a comment from the url...

```js
[
  [ 'word', 'background', 6, 15 ],
  [ ':', ':', 16 ],
  [ 'word', 'center/auto,url', 17, 31 ],
  [ '(', '(', 32 ],
  [ 'word', 'https', 33, 37 ],
  [ ':', ':', 38 ],
  [ 'comment', '//example.com/test.png)}', 39, 62, 'inline' ]
]
```

Running the same with the newline before the url() yields a better token list:

```js
[
  [ 'word', 'background', 6, 15 ],
  [ ':', ':', 16 ],
  [ 'word', 'center/auto,', 17, 28 ],
  [ 'space', '\n' ],
  [ 'word', 'url', 30, 32 ],
  [ 'brackets', '(https://example.com/test.png)', 33, 62 ],
  [ '}', '}', 63 ]
]
```

**Comment by jleclanche** [comment]
ok, so actually the `/` in `center/auto,url` is not the culprit. I can reproduce with anything that isn't exactly the word `url`. So for example, here, the first will succeed, the second will fail:

```css
  .test{background:url(https://example.com/test.png)}
  .test{background:testurl("https://example.com/test.png")}
  .test{background:testurl(https://example.com/test.png)}
```

Here's the token dump for all three, respectively:

```js 
// pass
// .test{background:url(https://example.com/test.png)}
  parse('.test{background:url(https://example.com/test.png)}')
  parse('.test{background:testurl("https://example.com/test.png")}')
  parse('.test{background:testurl(https://example.com/test.png)}')
[
  [ 'word', 'background', 6, 15 ],
  [ ':', ':', 16 ],
  [ 'word', 'url', 17, 19 ],
  [ 'brackets', '(https://example.com/test.png)', 20, 49 ],
  [ '}', '}', 50 ]
]

// pass
// .test{background:testurl("https://example.com/test.png")}
[
  [ 'word', 'background', 6, 15 ],
  [ ':', ':', 16 ],
  [ 'word', 'testurl', 17, 23 ],
  [ '(', '(', 24 ],
  [ 'string', '"https://example.com/test.png"', 25, 54 ],
  [ ')', ')', 55 ],
  [ '}', '}', 56 ]
]

// crash
// .test{background:testurl(https://example.com/test.png)}
[
  [ 'word', 'background', 6, 15 ],
  [ ':', ':', 16 ],
  [ 'word', 'testurl', 17, 23 ],
  [ '(', '(', 24 ],
  [ 'word', 'https', 25, 29 ],
  [ ':', ':', 30 ],
  [ 'comment', '//example.com/test.png)}', 31, 54, 'inline' ]
]
```


It seems `url` receives special treatment. BUT, in the case of `background:center/auto,url(...)`, `url` is not the detected word:

```js
  [ 'word', 'center/auto,url', 17, 31 ],
```

So... yeha, that comma is the culprit kinda. I think postcss might be at fault here? It's not tokenizing the comma properly.

**Comment by jleclanche** [comment]
@ai figured it out. `RE_WORD_END` is missing a comma in it.

You patched the default postcss tokenizer by adding a COMMA and a matching case, but you have not added a comma in RE_WORD_END. So when a comma is "attached" to a word, it is detected as a part of this word.

```js
const RE_WORD_END = /[\t\n\f\r !"#'():;@[\\\]{}]|\/(?=\*)/g
```

```
[
  [ 'word', 'background', 6, 15 ],
  [ ':', ':', 16 ],
  [ 'word', 'center/auto', 17, 27 ],
  [ 'word', ',', 28, 29 ],
  [ 'word', 'url', 29, 31 ],
  [ 'brackets', '(https://example.com/test.png)', 32, 61 ],
  [ '}', '}', 62 ]
]
```

**Comment by ai** [comment]
Great work. Seems like I forgot to backport a fix. Can you send a PR to save your name in the project history.

**Comment by jleclanche** [comment]
Sending a PR now.
