### ISSUE TITLE
cannot parse @mixin syntax ?

### ISSUE THREAD

**Issue by artkynet** [postcss/postcss-scss#24]
@mixin border-radius($radius) {
    ^
      -webkit-border-radius: $radius;
    
    ERROR in ./~/css-loader?sourceMap&modules&localIdentName=[name]_[local]_[hash:base64:3]!./~/postcss-loader?parser=postcss-scss!./src/components/SearchWidget/SearchWidget.scss
    Module build failed: TypeError: Cannot read property 'toString' of undefined
        at new Input

**Comment by ai** [comment]
Mixin is just a common at-rule for parser, so it supports it. Problem is in different place.

Please show a full stacktrace.

**Comment by artkynet** [comment]
@mixin border-radius($radius) {
  -webkit-border-radius: $radius;
  border-radius: $radius;
}

.box { @include border-radius(10px); }

it's using for react starter kit, but @mixin syntax cannot work.

**Comment by TrySound** [comment]
@artkynet Show whole error.

**Comment by artkynet** [comment]
ERROR in ./~/css-loader?sourceMap&modules&localIdentName=[name]_[local]_[hash:base64:3]!./~/postcss-loader?parser=postcss-scss!./src/components/Header/Header.scss
    postcss-mixins: /Users/user/react/src/components/variables.scss:13:1: Undefined mixin border-radius($radius)
    
    @mixin border-radius($radius) {
    ^
      -webkit-border-radius: $radius;
    
    ERROR in ./~/css-loader?sourceMap&modules&localIdentName=[name]_[local]_[hash:base64:3]!./~/postcss-loader?parser=postcss-scss!./src/components/Header/Header.scss
    Module build failed: TypeError: Cannot read property 'toString' of undefined
        at new Input (/Users/user/react/node_modules/postcss/lib/input.js:31:23)
        at parse (/Users/user/react/node_modules/postcss/lib/parse.js:22:17)
        at new LazyResult (/Users/user/react/node_modules/postcss/lib/lazy-result.js:61:24)
        at Processor.process (/Users/user/react/node_modules/postcss/lib/processor.js:34:16)
        at processCss (/Users/user/react/node_modules/css-loader/lib/processCss.js:188:11)
        at Object.module.exports (/Users/user/react/node_modules/css-loader/lib/loader.js:24:2)
     @ ./src/components/Header/Header.scss 2:18-220

**Comment by TrySound** [comment]
@artkynet Do you have something before mixin definition?

**Comment by artkynet** [comment]
@TrySound nothing... you can try the react starter kit, add the mixin syntax to /src/component/variables.scss

**Comment by TrySound** [comment]
@artkynet Which one?

**Comment by artkynet** [comment]
@TrySound https://github.com/kriasoft/react-starter-kit

**Comment by TrySound** [comment]
@artkynet Okay. The problem is css-loader somehow pass undefined instead of content string with css. I think you should open issue there.

**Comment by ai** [comment]
Yeap. Problem happens before PostCSS.

**Comment by ai** [comment]
BTW, why you use `postcss-mixins` for SCSS sources?

`postcss-mixins` *DOESN'T* process Sass mixins. It has different syntax and different ideology.

**Comment by artkynet** [comment]
@ai If I don't use postcss-mixins, it's going down:

ERROR in ./~/css-loader?sourceMap&modules&localIdentName=[name]_[local]_[hash:base64:3]!./~/postcss-loader?parser=postcss-scss!./src/components/App/App.scss
    Module build failed: Error: Cannot find module 'postcss-mixins'
        at Function.Module._resolveFilename (module.js:339:15)
        at Function.Module._load (module.js:290:25)
        at Module.require (module.js:367:17)
        at require (internal/module.js:16:19)
        at Object.<anonymous> (/Users/user/react/node_modules/precss/index.js:11:14)
        at Module._compile (module.js:413:34)
        at Module._extensions..js (module.js:422:10)
        at Object.require.extensions.(anonymous function) [as .js] (/Users/user/react/node_modules/babel-register/lib/node.js:136:7)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Module.require (module.js:367:17)
        at require (internal/module.js:16:19)
        at Object.plugins (webpack.config.js:102:7)
        at Object.module.exports (/Users/user/react/node_modules/postcss-loader/index.js:28:27)
     @ ./src/components/App/App.scss 2:18-217

**Comment by ai** [comment]
```
Module build failed: Error: Cannot find module 'postcss-mixins'
```

Looks like you still use this module in some part of config

**Comment by TrySound** [comment]
@artkynet Write issue in react kit

**Comment by artkynet** [comment]
@TrySound I will, thanks guys @ai

**Comment by artkynet** [comment]
@TrySound I try remove the 'postcss-mixins' module from /node_modules/precss/index.js in the react starter kit, now It look normal, but the @mixins syntax still have no parsed...

**Comment by artkynet** [comment]
@TrySound @ai The problem has been resolved! https://github.com/kriasoft/react-starter-kit/issues/461#issuecomment-188349208  thanks guys
