### ISSUE TITLE
Error when loading via postcss-cli

### ISSUE THREAD

**Issue by davidjbradshaw** [postcss/postcss-scss#25]
When I try and load this plugin via postcss-cli, it blows up with the following error message.

    /usr/local/lib/node_modules/postcss-cli/index.js:109
        plugin = plugin.postcss || plugin();
                                   ^

    TypeError: plugin is not a function
        at /usr/local/lib/node_modules/postcss-cli/index.js:109:32
        at Array.map (native)
        at Object.<anonymous> (/usr/local/lib/node_modules/postcss-cli/index.js:97:24)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Module.require (module.js:367:17)
        at require (internal/module.js:16:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/postcss-cli/bin/postcss:3:1)

**Comment by ben-eb** [comment]
You need to load this using the `syntax` flag.

https://github.com/postcss/postcss-cli#--syntax-s
