### ISSUE TITLE
Error when using Sass nested property syntax

### ISSUE THREAD

**Issue by stickel** [postcss/postcss-scss#31]
I'm running into this error message when I call stylelint on uncompiled Sass files in my project.
```shell
Error: Expected pseudo-class or pseudo-element
    at new error (/project/node_modules/postcss-selector-parser/dist/processor.js:27:23)
    at Parser.error (/project/node_modules/postcss-selector-parser/dist/parser.js:212:15)
    at Parser.pseudo (/project/node_modules/postcss-selector-parser/dist/parser.js:292:25)
    at Parser.parse (/project/node_modules/postcss-selector-parser/dist/parser.js:502:22)
    at Parser.loop (/project/node_modules/postcss-selector-parser/dist/parser.js:470:18)
    at new Parser (/project/node_modules/postcss-selector-parser/dist/parser.js:89:21)
    at Processor.process (/project/node_modules/postcss-selector-parser/dist/processor.js:24:21)
    at /project/node_modules/stylelint/dist/rules/selector-pseudo-element-case/index.js:48:10
    at /project/node_modules/postcss/lib/container.js:110:28
    at /project/node_modules/postcss/lib/container.js:73:26
```
After some digging, the error occurs when a Sass stylesheet has the following syntax:
```scss
.foo {
  flex: {
    grow: 1;
    shrink: 1;
  }
}
```
Which compiles to:
```css
.foo {
  flex-grow: 1;
  flex-shrink: 1;
}
```
The same error occurs with `font: { size: 12px; weight: bold; }` (and likely other nested properties). When this type of nesting is removed from the Sass file no error is reported.

**Comment by stickel** [comment]
This has also been reported here https://github.com/postcss/postcss-selector-parser/issues/64 as I wasn't sure which project would require the fix.

**Comment by ai** [comment]
Sorry, according stacktrace this issue is not related to common parser. It is only selector parser thing
