### ISSUE TITLE
Unable to use pocss-scss as a processor with gulp-postcss

### ISSUE THREAD

**Issue by Inori-Lover** [postcss/postcss-scss#33]
I'd like to use the scss plugin pack with gulp-postcss, as my first processor to be followed by a set of other cherry picked postcss plugins. and it throw error.

>```
gulp.task('sass', function () {
    return gulp.src('tpls/scss/bangumi-add.scss')
        .pipe( sourcemaps.init() )
        .pipe( postcss([ require('postcss-scss'),require('autoprefixer') ]) )
        .pipe( sourcemaps.write('.') )
        .pipe( gulp.dest('./dest') );
});
```


and it throws:
>```
[19:50:08] Using gulpfile E:\xampp\vcbs\src\gulpfile.js
[19:50:08] Starting 'sass'...
E:\xampp\vcbs\src\node_modules\gulp-postcss\node_modules\postcss\lib\processor.js:60
                throw new Error(i + ' is not a PostCSS plugin');
>                 ^
>
>Error: [object Object] is not a PostCSS plugin
  at Processor.normalize (E:\xampp\vcbs\src\node_modules\gulp-postcss\node_modules\postcss\lib\processor.js:60:23)
  at new Processor (E:\xampp\vcbs\src\node_modules\gulp-postcss\node_modules\postcss\lib\processor.js:23:29)
  at postcss (E:\xampp\vcbs\src\node_modules\gulp-postcss\node_modules\postcss\lib\postcss.js:55:12)
  at Transform.stream._transform (E:\xampp\vcbs\src\node_modules\gulp-postcss\index.js:47:5)
  at Transform._read (_stream_transform.js:167:10)
  at Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:301:12)
  at writeOrBuffer (_stream_writable.js:287:5)
  at Transform.Writable.write (_stream_writable.js:215:11)
  at DestroyableTransform.ondata (E:\xampp\vcbs\src\node_modules\gulp-sourcemaps\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:531:20)
  at emitOne (events.js:77:13)
  at DestroyableTransform.emit (events.js:169:7)
  at readableAddChunk (E:\xampp\vcbs\src\node_modules\gulp-sourcemaps\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:198:18)
  at DestroyableTransform.Readable.push (E:\xampp\vcbs\src\node_modules\gulp-sourcemaps\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:157:10)
  at DestroyableTransform.Transform.push (E:\xampp\vcbs\src\node_modules\gulp-sourcemaps\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:123:32)
  at DestroyableTransform.sourceMapInit [as _transform] (E:\xampp\vcbs\src\node_modules\gulp-sourcemaps\index.js:122:10)
  at DestroyableTransform.Transform._read (E:\xampp\vcbs\src\node_modules\gulp-sourcemaps\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:159:10)
  at DestroyableTransform.Transform._write (E:\xampp\vcbs\src\node_modules\gulp-sourcemaps\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:147:83)
  at doWrite (E:\xampp\vcbs\src\node_modules\gulp-sourcemaps\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:313:64)
  at writeOrBuffer (E:\xampp\vcbs\src\node_modules\gulp-sourcemaps\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:302:5)
  at DestroyableTransform.Writable.write (E:\xampp\vcbs\src\node_modules\gulp-sourcemaps\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:241:11)
  at write (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
  at flow (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:664:5)
  at emitNone (events.js:67:13)
  at DestroyableTransform.emit (events.js:166:7)
  at emitReadable_ (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:448:10)
  at emitReadable (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:444:5)
  at readableAddChunk (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:145:32)
  at afterTransform (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:101:12)
  at TransformState.afterTransform (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
  at DestroyableTransform.noop [as _transform] (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\through2.js:26:3)
  at DestroyableTransform.Transform._read (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
  at doWrite (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
  at writeOrBuffer (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)
  at write (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
  at flow (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:664:5)
  at emitNone (events.js:67:13)
  at DestroyableTransform.emit (events.js:166:7)
  at emitReadable_ (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:448:10)
  at emitReadable (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:444:5)
  at readableAddChunk (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:145:32)
  at afterTransform (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:101:12)
  at TransformState.afterTransform (E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
  at E:\xampp\vcbs\src\node_modules\gulp\node_modules\vinyl-fs\lib\src\getContents\bufferFile.js:12:5
  at FSReqWrap.readFileAfterClose [as oncomplete] (evalmachine.<anonymous>:380:3)
```

Do you have any suggestions on how to get this working, or a better configuration?

**Comment by ai** [comment]
postcss-scss is not a plugin. It is syntax. So you should use proper gulp-postcss options.

**Comment by Inori-Lover** [comment]
thx,sorry for stupid question.

**Comment by zrrtcs** [comment]
#10
