### ISSUE TITLE
mixin parse error

### ISSUE THREAD

**Issue by beyondghx** [postcss/postcss-scss#34]
I want to us postcss-scss to parse css file below, but i got some error. So I want to know why

```
/*test.css*/
/*icon mixin*/
@mixin live-icon {
  color: #fff;
  background-color: #FF8B30;
  border-radius: 3px;
  font-style: normal;
}

.icon{
  @include live-icon;
}

/*webpack config file*/
module.exports = {
    module: {
        loaders: [
            {
                test:   /\.css$/,
                loader: "style-loader!css-loader!postcss-loader"
            }
        ]
    },
    postcss: function (webpack) {
        return {
             plugins: [precss, autoprefixer({ browsers: ['> 1%', 'IE 8'] })],
             syntax: postScss
        }
    }
}
```

**Comment by beyondghx** [comment]
I got error like this:

```
ERROR in ./~/css-loader!./~/postcss-loader!./src/styles/test.css
postcss-mixins: /Users/beyondghx/Documents/Project/Demos/PostCss/react-boilerplate/src/styles/test.css:21:1: Undefined mixin live-icon
/*icon mixin*/
@mixin live-icon {
^
  color: #fff;

ERROR in ./~/css-loader!./~/postcss-loader!./src/styles/test.css
Module build failed: TypeError: Cannot read property 'toString' of undefined
    at new Input (/Users/beyondghx/Documents/Project/Demos/PostCss/react-boilerplate/node_modules/css-loader/node_modules/postcss/lib/input.js:31:23)
    at parse (/Users/beyondghx/Documents/Project/Demos/PostCss/react-boilerplate/node_modules/css-loader/node_modules/postcss/lib/parse.js:22:17)
    at new LazyResult (/Users/beyondghx/Documents/Project/Demos/PostCss/react-boilerplate/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:61:24)
    at Processor.process (/Users/beyondghx/Documents/Project/Demos/PostCss/react-boilerplate/node_modules/css-loader/node_modules/postcss/lib/processor.js:34:16)
    at processCss (/Users/beyondghx/Documents/Project/Demos/PostCss/react-boilerplate/node_modules/css-loader/lib/processCss.js:188:11)
    at Object.module.exports (/Users/beyondghx/Documents/Project/Demos/PostCss/react-boilerplate/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/styles/test.css 4:14-123
```

**Comment by TrySound** [comment]
@beyondghx `postcss-mixins: Undefined mixin live-icon`. That's because `postcss-mixins` is not the same as sass mixins.
Read documentation for more information about it https://github.com/postcss/postcss-mixins or use sass-loader instead. Also you can try to use another mixin plugin https://github.com/andyjansson/postcss-sassy-mixins

**Comment by beyondghx** [comment]
@TrySound Thanks，I know the `postcss-sassy-mixins` plugin,but the documentation of postcss-scss has below words:

> It simply parses mixins as custom at-rules & variables as properties, so that PostCSS plugins can then transform SCSS source code alongside CSS.

Is that mean I can use scss syntax(include mixins, variables and so on) in my css file and the `postcss-scss` plugin will transform it to the syntax the other plugins(just like `precss`, `postcss-mixins`) can parse? If not ,I'm sorry to said I don't know the real purpose of the `postcss-scss` plugin...Maybe you can point it out for me.Thanks~

**Comment by TrySound** [comment]
@beyondghx Nope. It's only parser, not processor. It can let you process scss sources with stylelint or something like this. Also you can use scss syntax for regular css but with single line comments.

**Comment by TrySound** [comment]
And yes, precss and postcss-mixins can use that ast.
