### ISSUE TITLE
Module build failed: TypeError: Invalid PostCSS Plugin found: [2]

### ISSUE THREAD

**Issue by SimonCheung1989** [postcss/postcss-scss#58]
Hi, my postcss.config.js like this
```
module.exports = {
    plugins: [
        require('postcss-sassy-mixins'),
        require('postcss-nested'),
        require('postcss-scss'),
        require('precss'),
        require('autoprefixer')
    ]
}
```
But got this error message
```

Child extract-text-webpack-plugin:

    ERROR in ./~/css-loader!./~/postcss-loader!./src/styles/index.scss
    Module build failed: TypeError: Invalid PostCSS Plugin found: [2]
        at C:\Users\43957841\workspace_VSC\demo-app\node_modules\postcss-load-plugins\lib\plugins.js:32:17
        at Array.forEach (native)
        at plugins (C:\Users\43957841\workspace_VSC\demo-app\node_modules\postcss-load-plugins\lib\plugins.js:21:15)
        at C:\Users\43957841\workspace_VSC\demo-app\node_modules\postcss-load-config\index.js:64:18
Done in 24.38s.
```

**Comment by ai** [comment]
postcss-scss is not a plugin, you need to set it as syntax option

**Comment by dave0688** [comment]
Can you please explain what I need to do in order to solve that? I'm stuck for hours on that now...

**Comment by ai** [comment]
@dave0688 

```diff
module.exports = {
+ parser: equire('postcss-scss')
  plugins: [
        require('postcss-sassy-mixins'),
        require('postcss-nested'),
-       require('postcss-scss'),
        require('precss'),
        require('autoprefixer')
    ]
}
```

**Comment by dave0688** [comment]
Thanks for your help! For some reason I have another problem now...:

```
[ERROR]  10% building modules 1/1 modules 0 active                                                               12% bui
lding modules 20/123 modules 103 active ...modules\rxjs\add\operator\debounce.js               38% building modules 235/
282 modules 46 active ...bootstrap\ng-bootstrap\modal\modal.js                     62% building modules 436/451 modules
15 active ...ules\rxjs\observable\dom\webSocket.js        4299ms building modules
[ERROR] 19ms sealing
[ERROR] 1ms optimizing
[ERROR] 0ms basic module optimization
[ERROR] 13ms module optimization
[ERROR] 0ms advanced module optimization
[ERROR] 0ms basic chunk optimization
[ERROR] 1ms chunk optimization
[ERROR] 0ms advanced chunk optimization
[ERROR] 0ms module and chunk tree optimization
[ERROR] 19ms module reviving
[ERROR] 2ms module order optimization
[ERROR] 3ms module id optimization
[ERROR] 1ms chunk reviving
[ERROR] 0ms chunk order optimization
[ERROR] 6ms chunk id optimization
[ERROR] 39ms hashing
[ERROR] 0ms module assets processing
[ERROR] 72ms chunk assets processing
[ERROR] 1ms additional chunk assets processing
[ERROR] 0ms recording
[ERROR] 9802ms additional asset processing
[ERROR] 0ms chunk asset optimization
[ERROR] 11ms asset optimization
× { Error: stdout maxBuffer exceeded
    at Socket.onChildStdout (child_process.js:263:14)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:554:20) cmd: 'mvnw package -DskipTests=true -B -Pprod' }
Execution complete
```

Do you have any idea? I would need your help again I guess, I'm sorry :)

**Comment by ai** [comment]
Have no idea :)

**Comment by dave0688** [comment]
Sorry to bother you here again, but I got massive problems starting my application out of nothing. It keeps giving me the following error: 

```
ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader/lib/loader.js!./src/main/webapp/content/scss/global.scss
Module build failed: TypeError: Invalid PostCSS Plugin found: [0]
    at C:\Entwicklung\git\Coinlender\node_modules\postcss-load-plugins\lib\plugins.js:32:17
    at Array.forEach (native)
    at plugins (C:\Entwicklung\git\Coinlender\node_modules\postcss-load-plugins\lib\plugins.js:21:15)
    at C:\Entwicklung\git\Coinlender\node_modules\postcss-loader\node_modules\postcss-load-config\index.js:64:18
 @ ./src/main/webapp/content/scss/global.scss 4:14-194 13:2-17:4 14:20-200
 @ multi (webpack)-dev-server/client?http://localhost:9060 webpack/hot/dev-server ./src/main/webapp/content/scss/global.scss
```

My postcss.config.js is empty (since it worked before) and I'm not familiar with the concept of PostCSS. Do you have any hint what I need to do in order to solve that? And, do I need a PostCSS plugin at all? Why does it keep searching for some postcss plugin when I have developed my application for like 6 weeks now and never had problems with that?

Can you please help me?

**Comment by ai** [comment]
@dave0688 ask question in support chat https://gitter.im/postcss/postcss
