### ISSUE TITLE
Possible require("supports-color") dependency issue in v2.0.0

### ISSUE THREAD

**Issue by jtclegg** [postcss/postcss-scss#96]
I've just installed v.2.0.0 and now receive an error when setting `parser: require('postcss-scss')` in gruntfile.js. If I revert back to v^1.0.0 the error does not occur. The problem may be on my side but indications point to bad .json or .js in supports-color, which is preventing postcss-scss from running.

Here's the log:

```
my gruntfile.js:88
>> parser: require('postcss-scss')

css-syntax-error.js:6
>> register("supports-color")

Loading "gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token {
>>   at exports.runInThisContext (vm.js:53:16)
>>   at Module._compile (module.js:373:25)
>>   at Object.Module._extensions..js (module.js:416:10)
>>   at Module.load ({projectFolder}\node_modules\coffeescript\lib\coffee-script\register.js:45:36)
>>   at Function.Module._load (module.js:300:12)
>>   at Module.require (module.js:353:17)
>>   at require (internal/module.js:12:17)
>>   at Object.<anonymous> ({projectFolder}\node_modules\postcss\lib\css-syntax-error.js:6:45)
>>   at Module._compile (module.js:409:26)
>>   at Object.Module._extensions..js (module.js:416:10)
>>   at Module.load ({projectFolder}\node_modules\coffeescript\lib\coffee-script\register.js:45:36)
>>   at Function.Module._load (module.js:300:12)
>>   at Module.require (module.js:353:17)
>>   at require (internal/module.js:12:17)
>>   at Object.<anonymous> ({projectFolder}\node_modules\postcss\lib\input.js:6:46)
>>   at Module._compile (module.js:409:26)
>>   at Object.Module._extensions..js (module.js:416:10)
>>   at Module.load ({projectFolder}\node_modules\coffeescript\lib\coffee-script\register.js:45:36)
>>   at Function.Module._load (module.js:300:12)
>>   at Module.require (module.js:353:17)
>>   at require (internal/module.js:12:17)
>>   at Object.<anonymous> ({projectFolder}\node_modules\postcss-scss\lib\scss-parse.js:3:13)
>>   at Module._compile (module.js:409:26)
>>   at Object.Module._extensions..js (module.js:416:10)
>>   at Module.load ({projectFolder}\node_modules\coffeescript\lib\coffee-script\register.js:45:36)
>>   at Function.Module._load (module.js:300:12)
>>   at Module.require (module.js:353:17)
>>   at require (internal/module.js:12:17)
>>   at Object.<anonymous> ({projectFolder}\node_modules\postcss-scss\lib\scss-syntax.js:4:13)
>>   at Module._compile (module.js:409:26)
>>   at Object.Module._extensions..js (module.js:416:10)
>>   at Module.load ({projectFolder}\node_modules\coffeescript\lib\coffee-script\register.js:45:36)
>>   at Function.Module._load (module.js:300:12)
>>   at Module.require (module.js:353:17)
>>   at require (internal/module.js:12:17)
>>   at Object.module.exports ({projectFolder}\gruntfile.js:88:18)
>>   at loadTask ({projectFolder}\node_modules\grunt\lib\grunt\task.js:315:10)
>>   at Task.task.init ({projectFolder}\node_modules\grunt\lib\grunt\task.js:434:5)
>>   at Object.grunt.tasks ({projectFolder}\node_modules\grunt\lib\grunt.js:111:8)
>>   at Object.module.exports [as cli] ({projectFolder}\node_modules\grunt\lib\grunt\cli.js:27:9)
>>   at Object.<anonymous> ({roamingProfile}\npm\node_modules\grunt-cli\bin\grunt:45:20)
>>   at Module._compile (module.js:409:26)
>>   at Object.Module._extensions..js (module.js:416:10)
>>   at Module.load (module.js:343:32)
>>   at Function.Module._load (module.js:300:12)
>>   at Function.Module.runMain (module.js:441:10)
>>   at startup (node.js:139:18)
>>   at node.js:968:3
```

**Comment by ai** [comment]
Show `node --version` output

**Comment by jtclegg** [comment]
node v.4.4.0

**Comment by ai** [comment]
Node.js 4 doesn't have security updates anymore. This is why we dropped Node.js 4 support in new versions.

I highly recommend to update it. It is dangerous.

**Comment by jtclegg** [comment]
Of course. My mistake for missing the fact node had drifted so far out of date. Thanks for pointing out.
